on:
  check_suite:
    type: ['completed']
    branches:
      - master
  pull_request:
    type: ['opened']
  
name: Branch Guard
jobs:
  branch-guard:
    name: Branch Guard Check
    runs-on: ubuntu-latest
    steps:
    - uses: cirrus-actions/branch-guard@v0.9
      with:
        appsToCheck: Cirrus CI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
