on:
  check_suite: # to update all PRs upon a Check Suite completion
    type: ['completed']
  pull_request: # to update newly open PRs
    type: ['opened', 'synchronize']
  
name: Branch Guard
jobs:
  branch-guard:
    name: Branch Guard
    if: github.event.check_suite.head_branch == 'master' || github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
    - uses: cirrus-actions/branch-guard@v1
      with:
        appsToCheck: Cirrus CI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
