name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: docker.pkg.github.com/${{ github.event.repository.full_name }}/mkdocs:${{ github.event.release.tag_name }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}:  
      - name: Push to GitHub Packages
        run: docker push docker.pkg.github.com/${{ github.event.repository.full_name }}/mkdocs:${{ github.event.release.tag_name }}
