on:
  check_suite:
    type: ['completed']

name: Email about Cirrus CI failures
jobs:
  continue:
    name: Cirrus CI Failed
    if: github.event.check_suite.app.name == 'Cirrus CI' && github.event.check_suite.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
