name: tests
on: [push, pull_request]

jobs:
  run:
    name: Run
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Sleep
      run: sleep 120
