name: tests
on: [push, pull_request]

jobs:
  run:
    name: Run
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: Sleep
      run: sleep 120
